### ISSUE TITLE
Soy GNU/Kernel

### ISSUE THREAD

**Issue by KenethSandoval** [faztcommunity/first-pr#1]
Yo elegí el método:  test

**Comment by DanoRysJan** [comment]
No encontré tu PR

**Comment by KenethSandoval** [comment]
Me no hay diferencia en mi rama y no me deja hacer el PR

**Comment by EnzoDiazDev** [comment]
Asegurate que las historias estén relacionadas con tu repositorio. Hace un pull al repositorio original. 
`git remote add upstream https://github.com/faztcommunity/first-pr.git`
`git pull upstream`
resolvé los conflictos
`git push origin main` *(o master)*
Y ahi podés hacer el pull request sin conflictos

**Comment by DanoRysJan** [comment]
cORR
